version: 2.1
jobs:
  Build-and-Test:
    docker:
      - image: grafana/k6
    steps:
      - checkout
      - run: 
          name: "Preparing Test"
          command: "mkdir reports"
      - run:
          name: "Run Test"
          command: |
            cd tests/
            k6 run run_test.js --summary-export reports/report.json
      - store_artifacts:
          path: report.json

workflows:
  Loadtest-Workflow:
    jobs:
      - Build-and-Test
