version: 2.1
jobs:
  Build-and-Test:
    docker:
      - image: grafana/k6
    steps:
      - checkout
      - run: 
          name: "Preparing Test"
          command: mkdir reports
      - run:
          name: "Run Test"
          command: k6 run test.js --log-output file=reports/k6.log --log-format json --summary-export reports/report.json -q
      - store_artifacts:
          path: reports/

workflows:
  Loadtest-Workflow:
    jobs:
      - Build-and-Test
